# Generated by Django 5.2.7 on 2025-11-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
